name: Build

on: [push, workflow_dispatch, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build project
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          nmake /nologo
      - name: Copy license and ini file to bin
        run: |
          copy LICENSE "bin/FLSharp_LICENSE.txt"
          copy FLSharp.ini "bin"
      - name: Upload release build as artifact
        uses: actions/upload-artifact@v7
        with:
          name: FLSharp
          path: |
            bin/FLSharp.dll
            bin/FLSharp.pdb
            bin/FLSharp.ini
            bin/FLSharp_LICENSE.txt
