name: Build

on: [push, workflow_dispatch, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: win32
      - name: Build project
        run: |
          nmake /nologo
      - name: Copy license and ini file to bin
        run: |
          copy LICENSE "bin/FLSharp_LICENSE.txt"
          copy FLSharp.ini "bin"
      - name: Upload release build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: FLSharp release build
          path: |
            bin/FLSharp.dll
            bin/FLSharp.pdb
            bin/FLSharp.ini
            bin/FLSharp_LICENSE.txt
