name: Build

on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: win32
      - name: Build project
        run: |
          nmake /nologo
      - name: Run tests
        run: |
          nmake /nologo test
