name: Test

on: [push, workflow_dispatch, pull_request]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: win32
      - name: Download Catch2 test files
        uses: robinraju/release-downloader@v1
        with:
          repository: 'catchorg/Catch2'
          tag: 'v3.9.1'
          fileName: '{catch_amalgamated.cpp,catch_amalgamated.hpp}'
          out-file-path: 'test'
      - name: Run tests
        run: |
          nmake /nologo test
